#!/bin/bash
# My first script

nasm -f elf driver6.asm
nasm -f elf Miller_sub1.asm
nasm -f elf Miller_sub2.asm
nasm -f elf Miller_sub3.asm
nasm -f elf Miller_sub4.asm

nasm -f elf printArray.asm

gcc driver6.o Miller_sub1.o Miller_sub2.o Miller_sub3.o Miller_sub4.o printArray.o -o mil6_exe

./mil6_exe

rm driver6.o
rm Miller_sub1.o
rm Miller_sub2.o
rm Miller_sub3.o
rm Miller_sub4.o
rm printArray.o
rm mil6_exe

echo "Script Complete"
